---

- name: Add Projects
  awx.awx.tower_project:
    name: "{{ item.name }}"
    description: "{{ item.description | default(omit) }}"
    scm_type: "{{ item.scm_type }}"
    scm_url: "{{ item.scm_url }}"
    local_path: "{{ item.local_path | default(omit) }}"
    scm_branch: "{{ item.scm_branch }}"
    scm_refspec: "{{ item.scm_refspec | default(omit) }}"
    scm_credential: "{{ item.scm_credential | default(omit) }}"
    scm_clean: "{{ item.scm_clean | default(omit) }}"
    scm_delete_on_update: "{{ item.scm_delete_on_update }}"
    scm_update_on_launch: "{{ item.scm_update_on_launch }}"
    scm_update_cache_timeout: "{{ item.scm_update_cache_timeout | default(omit) }}"
    allow_override: "{{ item.allow_override | default(omit) }}"
    job_timeout: "{{ item.job_timeout | default(omit) }}"
    custom_virtualenv: "{{ item.custom_virtualenv | default(omit) }}"
    organization: "{{ item.organization }}"
    state: "{{ item.state | default('present') }}"
    wait: "{{ item.wait | default(omit) }}"
    notification_templates_started: "{{ item.notification_templates_started | default(omit) }}"
    notification_templates_success: "{{ item.notification_templates_success | default(omit) }}"
    notification_templates_error: "{{ item.notification_templates_error | default(omit) }}"
    tower_username: "{{ tower_username | default(omit) }}"
    tower_password: "{{ tower_password | default(omit) }}"    
    tower_oauthtoken: "{{ tower_oauthtoken | default(omit) }}"
    tower_host: "{{ tower_server }}"
    tower_verify_ssl: "{{ tower_verify_ssl | default('yes') }}"
  with_items: "{{ projects }}"
  no_log: "{{ tower_genie_projects_secure_logging }}"
  