---
tower_hostname: ""
tower_oauthtoken: ""
tower_validate_certs: false
tower_genie_organizations_secure_logging: "{{tower_genie_secure_logging | default(false)}}"
tower_organizations:
  - name: Default
    description: Default
