---
- name: Bring in vaulted Ansible Tower secrets
  include_vars: vars/tower-secrets.yml
  when: tower_secrets
  no_log: true

- name: Create Ansible Tower Team
  tower_team:
    name: "{{ tower_team_name }}"
    description: "{{ tower_team_desc }}"
    organization: "{{ tower_org }}"
    validate_certs: "{{ validate_certs }}"
    state: "present"
