---
- name: Add organizations
  awx.awx.tower_organization:
    name: "{{ item.name }}"
    description: "{{ item.description | default(omit) }}"
    custom_virtualenv: "{{ item.custom_virtualenv | default(omit) }}"
    max_hosts: "{{ item.max_hosts | default(omit) }}"
    notification_templates_started: "{{ item.notification_templates_started | default(omit) }}"
    notification_templates_success: "{{ item.notification_templates_success | default(omit) }}"
    notification_templates_error: "{{ item.notification_templates_error | default(omit) }}"  
    notification_templates_approvals: "{{ item.notification_templates_approvals | default(omit) }}"
    state: "{{ item.state | default('present') }}"
    tower_username: "{{ tower_username | default(omit) }}"
    tower_password: "{{ tower_password | default(omit) }}"
    tower_oauthtoken: "{{ tower_oauthtoken | default(omit) }}"
    tower_host: "{{ tower_server }}"
    tower_verify_ssl: "{{ tower_verify_ssl | default('omit') }}"
  with_items: "{{ organizations }}"
  no_log: "{{ tower_genie_organizations_secure_logging }}"